#!/usr/bin/env python3
"""Migrate Personal Ops habit definitions and completions to Habitify.

Dry-run is the default. Pass --apply to create habits and upload history.
Failures generated by the bot's nightly auto-miss are deliberately not imported:
Habitify can derive incomplete scheduled days, while those synthetic events are
not reliable enough to become permanent explicit failures.
"""

from __future__ import annotations

import argparse
import os
import re
import sqlite3
import sys
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass
from datetime import date
from pathlib import Path

from dotenv import load_dotenv

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "ops"))

from habitify import HabitifyClient, HabitifyError  # noqa: E402


NON_SHABBAT_DAYS = [0, 1, 2, 3, 4, 5]  # Habitify: Sunday=0 ... Saturday=6


@dataclass(frozen=True)
class MigrationRule:
    local_name: str
    aliases: tuple[str, ...]
    remote_name: str | None = None
    periodicity: str = "daily"
    goal_value: int = 1
    goal_unit: str = "rep"
    import_completions: bool = True
    archive_after_import: bool = False


RULES = (
    MigrationRule("Take morning meds (before anything else)", ("Take morning meds",)),
    MigrationRule(
        "Daily walk (7000 steps minimum, includes walk to shul)",
        ("Daily walk",),
        remote_name="Step Count",
        goal_value=7000,
        goal_unit="step",
        import_completions=False,  # Apple Health supplies authoritative history.
    ),
    MigrationRule("Shacharit (07:00–08:00)", ("Shacharit",)),
    MigrationRule("Anki (minimum daily streak)", ("Anki",)),
    MigrationRule(
        "Drink at least 1 liter of water a day",
        ("Drink at least 1 liter of water a day",),
    ),
    MigrationRule(
        "Eat at least 100 grams of protein.",
        ("Eat at least 100 grams of protein.",),
    ),
    MigrationRule(
        "10:00–11:00 Yoma chavrusa",
        ("Yoma chavrusa", "10:00–11:00 Yoma chavrusa"),
    ),
    MigrationRule(
        "Strength training — 3x/week minimum",
        ("Strength training",),
        remote_name="Core Training",
        periodicity="weekly",
        goal_value=3,
    ),
    MigrationRule(
        "Weigh in — at least 3x/week, morning, log in Apple Health",
        ("Weigh in",),
        periodicity="weekly",
        goal_value=3,
    ),
    MigrationRule(
        "Writing output — at least 3 times per week (genealogy, dailyderja, or technical)",
        ("Writing output",),
        periodicity="weekly",
        goal_value=3,
    ),
    MigrationRule(
        "Shnayim Mikra vEchad Targum", ("Shnayim Mikra vEchad Targum",)
    ),
    MigrationRule("brush teeth", ("brush teeth",), remote_name="Brush teeth"),
    MigrationRule(
        "Call Rebbe at 5:30 am.",
        ("Call Rebbe at 5:30 am.",),
        archive_after_import=True,
    ),
    MigrationRule("have protein shake", ("have protein shake",)),
    MigrationRule("wash 5 dishes", ("wash 5 dishes",)),
    MigrationRule("tefillin", ("tefillin",), remote_name="Tefillin"),
    MigrationRule(
        "wake up and get out of bed before 7",
        ("wake up and get out of bed before 7",),
    ),
)


def normalize_name(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", " ", value.casefold()).strip()


def python_days_to_habitify(csv: str) -> list[int]:
    """Convert Python Monday=0 weekdays to Habitify Sunday=0 weekdays."""
    if not csv:
        return NON_SHABBAT_DAYS.copy()
    return sorted({(int(day) + 1) % 7 for day in csv.split(",") if day})


def description_for(row: sqlite3.Row) -> str:
    lines = ["Imported from Personal Ops.", f"Section: {row['section']}"]
    if row["cue"]:
        lines.append(f"Cue: {row['cue']}")
    if row["identity"]:
        lines.append(f"Identity: {row['identity']}")
    return "\n".join(lines)


def habit_payload(row: sqlite3.Row, rule: MigrationRule, start_date: str) -> dict:
    return {
        "name": rule.local_name,
        "type": "good",
        "description": description_for(row),
        "occurrence": {
            "type": "weekDays",
            "days": python_days_to_habitify(row["days"]),
        },
        "startDate": start_date,
        "goal": {
            "periodicity": rule.periodicity,
            "value": rule.goal_value,
            "unit": rule.goal_unit,
        },
    }


def load_local(db_path: Path) -> tuple[dict[str, sqlite3.Row], dict[str, set[str]]]:
    conn = sqlite3.connect(f"file:{db_path}?mode=ro", uri=True)
    conn.row_factory = sqlite3.Row
    rows = conn.execute(
        "SELECT * FROM habits WHERE tracked = 1 ORDER BY position, id"
    ).fetchall()
    habits = {row["name"]: row for row in rows}
    completions: dict[str, set[str]] = {rule.local_name: set() for rule in RULES}
    alias_owner = {
        normalize_name(alias): rule.local_name for rule in RULES for alias in rule.aliases
    }
    for row in conn.execute(
        "SELECT date, content FROM entries WHERE tag = 'habit' ORDER BY date, id"
    ):
        owner = alias_owner.get(normalize_name(row["content"]))
        if owner:
            completions[owner].add(row["date"])
    conn.close()
    return habits, completions


def find_remote(rule: MigrationRule, remote_habits: list[dict]) -> dict | None:
    wanted = normalize_name(rule.remote_name or rule.local_name)
    return next((h for h in remote_habits if normalize_name(h["name"]) == wanted), None)


def earliest_for(completions: set[str]) -> str:
    return min(completions) if completions else date.today().isoformat()


def existing_statuses(
    client: HabitifyClient, habit_id: str, start: str, end: str
) -> dict[str, str]:
    stats = client.statistics(habit_id, start, end)
    return {
        item["date"]: item["status"]
        for item in stats.get("dailyProgress", [])
        if item.get("status") != "inprogress"
    }


def migrate(
    apply: bool,
    db_path: Path,
    delay: float,
    workers: int,
    repair_archived: bool,
) -> int:
    load_dotenv(ROOT / ".env")
    api_key = os.environ.get("HABITIFY_API_KEY", "")
    if not api_key:
        print("HABITIFY_API_KEY is missing", file=sys.stderr)
        return 2

    local_habits, completions = load_local(db_path)
    missing_rules = [rule.local_name for rule in RULES if rule.local_name not in local_habits]
    unruled = sorted(set(local_habits) - {rule.local_name for rule in RULES})
    if missing_rules or unruled:
        print(f"Migration manifest mismatch. Missing: {missing_rules}; unruled: {unruled}")
        return 2

    client = HabitifyClient(api_key)
    remote_habits = client.list_habits()
    verb = "APPLY" if apply else "DRY RUN"
    print(f"Habitify migration: {verb}")
    print(f"Remote habits before migration: {len(remote_habits)}")

    created = uploaded = already_present = conflicts = deferred = 0
    for rule in RULES:
        row = local_habits[rule.local_name]
        dates = completions[rule.local_name]
        remote = find_remote(rule, remote_habits)
        destination = rule.remote_name or rule.local_name
        action = "match" if remote else "create"
        import_count = len(dates) if rule.import_completions else 0
        print(
            f"- {rule.local_name} -> {destination}: {action}; "
            f"{import_count} completion dates"
            + ("; archive afterward" if rule.archive_after_import else "")
            + ("; Health history wins" if not rule.import_completions else "")
        )
        if not apply:
            continue

        just_created = remote is None
        if just_created:
            remote = client.create_habit(
                habit_payload(row, rule, earliest_for(dates))
            )
            remote_habits.append(remote)
            created += 1
            print(f"  created {remote['name']}")
            # Habitify's read indexes can briefly lag behind a successful create.
            time.sleep(1.0)

        if (
            rule.import_completions
            and dates
            and remote.get("startDate", date.today().isoformat()) > min(dates)
        ):
            client.update_habit(remote["id"], {"startDate": min(dates)})
            remote["startDate"] = min(dates)
            print(f"  moved start date to {min(dates)} for historical import")
            time.sleep(1.0)

        if rule.archive_after_import and remote.get("isArchived"):
            if repair_archived:
                # Archived statistics omit dailyProgress, and the complete
                # endpoint accepts duplicate same-day values. Reset each known
                # date before writing exactly one canonical completion.
                for index, target_date in enumerate(sorted(dates), 1):
                    client.undo(remote["id"], target_date)
                    client.complete(remote["id"], target_date)
                    if index % 5 == 0 or index == len(dates):
                        print(f"  repaired {index}/{len(dates)} archived dates")
                uploaded += len(dates)
            else:
                print("  archived history preserved (not re-uploaded)")
            continue

        if rule.import_completions and dates:
            statuses = {}
            if not just_created:
                try:
                    statuses = existing_statuses(
                        client, remote["id"], min(dates), max(dates)
                    )
                except HabitifyError as exc:
                    if exc.status != 404:
                        raise
            pending: list[tuple[str, str | None]] = []
            for target_date in sorted(dates):
                status = statuses.get(target_date)
                if status == "completed":
                    already_present += 1
                    continue

                pending.append((target_date, status))

            def upload(item: tuple[str, str | None]) -> tuple[str, str | None, str]:
                target_date, status = item
                try:
                    # Backdating a habit makes Habitify *display* all earlier due
                    # days as failed before any log exists. A known local
                    # completion must therefore be attempted even when statistics
                    # currently say failed; only a 409 proves a real log conflict.
                    client.complete(remote["id"], target_date)
                    if delay:
                        time.sleep(delay)
                    return target_date, status, "uploaded"
                except HabitifyError as exc:
                    if exc.status == 409:
                        return target_date, status, "conflict"
                    if exc.status in {0, 429, 500, 502, 503, 504}:
                        return target_date, status, "deferred"
                    raise

            with ThreadPoolExecutor(max_workers=workers) as pool:
                futures = [pool.submit(upload, item) for item in pending]
                for index, future in enumerate(as_completed(futures), 1):
                    target_date, status, outcome = future.result()
                    if outcome == "uploaded":
                        uploaded += 1
                    elif outcome == "deferred":
                        deferred += 1
                    elif status in {"failed", "skipped"}:
                        conflicts += 1
                        print(f"  kept explicit {status} on {target_date}")
                    else:
                        already_present += 1
                    if index % 25 == 0 or index == len(futures):
                        print(f"  processed {index}/{len(futures)} pending dates")

        if rule.archive_after_import and not remote.get("isArchived"):
            client.archive(remote["id"])
            remote["isArchived"] = True
            print(f"  archived {remote['name']}")

    if apply:
        print(
            f"Done: created={created}, uploaded={uploaded}, "
            f"already_present={already_present}, conflicts_preserved={conflicts}, "
            f"deferred={deferred}"
        )
    else:
        print("No changes made. Re-run with --apply to migrate.")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--apply", action="store_true")
    parser.add_argument(
        "--db", type=Path, default=ROOT / "ops" / "log" / "ops.db"
    )
    parser.add_argument(
        "--delay",
        type=float,
        default=0.0,
        help="Optional delay after each write.",
    )
    parser.add_argument(
        "--workers",
        type=int,
        default=2,
        help="Concurrent upload requests; two avoids overloading Habitify writes.",
    )
    parser.add_argument(
        "--repair-archived",
        action="store_true",
        help="Reset and rewrite known dates for archived migrated habits.",
    )
    args = parser.parse_args()
    return migrate(
        args.apply,
        args.db,
        args.delay,
        args.workers,
        args.repair_archived,
    )


if __name__ == "__main__":
    raise SystemExit(main())
